CREATE TABLE tour_package_option_capacity_price
(
    id                              bigserial PRIMARY KEY,
    created_by                      VARCHAR(255),
    last_modified_by                VARCHAR(255),
    created_at                      TIMESTAMP,
    updated_at                      TIMESTAMP,
    version                         INTEGER,
    deleted                         BOOLEAN,
    rack_rate                       NUMERIC,
    corporate_rate                  NUMERIC,
    corporate_rate_discount_percent NUMERIC,
    ghuddy_commission_percent       NUMERIC,
    ghuddy_commission_amount        NUMERIC,
    shurjo_commission_amount        NUMERIC,
    shurjo_commission_percent       NUMERIC,
    ghuddy_website_black_price      NUMERIC,
    ghuddy_subsidy_amount           NUMERIC,
    ghuddy_subsidy_percent          NUMERIC,
    ghuddy_website_red_price        NUMERIC,
    total_discount_percent          NUMERIC,
    total_shurjo_commission_amount  NUMERIC,
    total_ghuddy_commission_amount  NUMERIC,
    total_ghuddy_commission_percent NUMERIC,
    total_seats                     BIGINT,
    bookable_seats                  BIGINT,
    package_option_id               INT,
    FOREIGN KEY (package_option_id) REFERENCES tour_package_option (id)
);
