CREATE TABLE tour_package_option_capacity_price_filter
(
    id                                          bigserial PRIMARY KEY,
    created_by                                  VARCHAR(255),
    last_modified_by                            VARCHAR(255),
    created_at                                  TIMESTAMP,
    updated_at                                  TIMESTAMP,
    version                                     INTEGER,
    deleted                                     BOOLEAN,
    policy_name                                 TEXT,
    tour_date                                   DATE,
    capacity_price_id                           INT,
    policy_type                                 VARCHAR(255),
    delta_rack_rate                             NUMERIC,
    delta_corporate_rate                        NUMERIC,
    delta_corporate_rate_discount_percent_point NUMERIC,
    delta_ghuddy_commission_percent_point       NUMERIC,
    delta_ghuddy_commission_amount              NUMERIC,
    delta_shurjo_commission_percent_point       NUMERIC,
    delta_shurjo_commission_amount              NUMERIC,
    delta_ghuddy_website_black_price            NUMERIC,
    delta_ghuddy_website_red_price              NUMERIC,
    delta_total_discount_percent_point          NUMERIC,
    delta_ghuddy_subsidy_amount                 NUMERIC,
    delta_ghuddy_subsidy_percent_point          NUMERIC,
    delta_total_ghuddy_commission_amount        NUMERIC,
    delta_total_ghuddy_commission_percent_point NUMERIC,
    delta_total_shurjo_commission_amount        NUMERIC,
    delta_total_seats                           BIGINT,
    delta_bookable_seats                        BIGINT,
    FOREIGN KEY (capacity_price_id) REFERENCES tour_package_option_capacity_price (id)
);
