insert into public.tour_package (id, created_by, created_at, deleted, last_modified_by, updated_at, version, active, tour_package_name, subscribed_tour_id, tour_package_type_id, description, is_food_included, is_accommodation_included, is_transportation_included, is_transfer_included, package_price_per_person, total_package_price)
values  (1, null, null, false, null, null, 0, null, 'Bandarban Tour - 2 Days 1 Night - Couple Package', 1, 1, 'tour package description', false, false, false, false, 300.00, null),
        (2, null, null, false, null, null, 0, null, 'Bandarban Tour - 2 Days 1 Night - Couple Package', 1, 1, 'tour package description', false, false, false, false, 300.00, null),
        (3, null, null, false, null, null, 0, null, 'Bandarban Tour - 2 Days 1 Night - Couple Package', 1, 1, 'tour package description', false, false, false, false, 300.00, null),
        (4, null, null, false, null, null, 0, null, 'Bandarban Tour - 2 Days 1 Night - Couple Package', 1, 1, 'tour package description', false, false, false, false, 300.00, null),
        (5, null, null, false, null, null, 0, null, 'Bandarban Tour - 2 Days 1 Night - Couple Package', 1, 1, 'tour package description', false, false, false, false, 300.00, null),
        (6, null, null, false, null, null, 0, null, 'Bandarban Tour - 2 Days 1 Night - Couple Package', 1, 1, 'tour package description', false, false, false, false, 600.00, 300),
        (7, null, null, false, null, null, 0, null, 'Bandarban Tour - 2 Days 1 Night - Couple Package', 1, 1, 'tour package description', false, false, false, false, 1800.00, 300),
        (8, null, null, false, null, null, 0, null, 'Bandarban Tour - 2 Days 1 Night - Couple Package', 1, 1, 'tour package description', false, false, false, false, 3600.00, 300),
        (9, null, null, false, null, null, 0, null, 'Bandarban Tour - 2 Days 1 Night - Couple Package', 1, 1, 'tour package description', false, false, false, false, 1800.00, 300),
        (10, null, null, false, null, null, 0, null, 'Bandarban Tour - 2 Days 1 Night - Couple Package', 1, 1, 'tour package description', false, false, false, false, 1400.00, 300),
        (11, null, null, false, null, null, 0, null, 'Bandarban Tour - 2 Days 1 Night - Couple Package', 1, 1, 'tour package description', false, false, false, false, 2000.00, 300),
        (13, null, null, false, null, null, 0, null, 'Bandarban Tour - 2 Days 1 Night - Couple Package', 1, 1, 'tour package description', false, false, false, false, 1080.00, 300),
        (14, null, null, false, null, null, 0, null, 'Bandarban Tour - 2 Days 1 Night - Couple Package', 1, 1, 'tour package description', false, false, false, false, 1080.00, 300),
        (15, null, null, false, null, null, 0, null, 'Bandarban Tour - 2 Days 1 Night - Couple Package', 1, 1, 'tour package description', false, false, false, false, 1080.00, 300),
        (16, null, null, false, null, null, 0, null, 'Bandarban Tour - 2 Days 1 Night - Couple Package', 1, 1, 'tour package description', false, false, false, false, 1080.00, 300),
        (17, null, null, false, null, null, 0, null, 'Bandarban Tour - 2 Days 1 Night - Couple Package', 1, 1, 'tour package description', false, false, false, false, 1080.00, 300),
        (18, null, null, false, null, null, 0, null, 'Bandarban Tour - 2 Days 1 Night - Couple Package', 1, 1, 'tour package description', false, false, false, false, 1080.00, 300),
        (19, null, null, false, null, null, 0, null, 'Bandarban Tour - 2 Days 1 Night - Couple Package', 1, 1, 'tour package description', false, false, false, false, 1080.00, 300);